# Generated by Django 2.2.7 on 2019-12-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='emails',
            new_name='email',
        ),
    ]
